#!/usr/bin/env python3
"""gen_adapters — repackage the skills for harnesses that are not Claude Code.

The knowledge is portable; only the discovery mechanism is not. Claude Code (and
Codex / Copilot CLI / Gemini CLI via ~/.agents/skills) reads SKILL.md directories
and loads a skill lazily by its description. Cursor, Windsurf, Continue and Cline
want their own rule format. Copilot-in-IDE, Aider and Zed want ONE file — and for
those, concatenating 27k words is the wrong answer: it burns the context the work
needs.

So this generates two shapes:

  per-skill rules   Cursor / Windsurf / Continue / Cline — the harness still picks
                    a skill by description, lazily, exactly like Claude Code.
  compressed router Copilot / AGENTS.md / Aider / Zed — the routing table, the nine
                    most-violated laws, the escalation ladder and the limits, with
                    file paths to the full skills. ~1.5k words instead of 27k;
                    the agent reads the rest on demand.

Plus CI wiring, because a harness that cannot hold the rules in context can still
be held to them by a non-zero exit code.

    python gen_adapters.py --out .                       # every target
    python gen_adapters.py --out . --targets cursor,ci
    python gen_adapters.py --out . --stack-path vendor/telegram-stack
    python gen_adapters.py --list
    python gen_adapters.py --out /tmp/x --dry-run

Exit: 0 ok, 1 generation error, 2 usage error.
"""
from __future__ import annotations

import argparse
import pathlib
import re
import sys
from dataclasses import dataclass, field

BANNER = ("GENERATED by telegram-stack/scripts/gen_adapters.py. Do not edit.\n"
          "Change skills/ and regenerate, or your edit disappears on the next run.")

# Same banner with every line commented. A two-line banner behind a single '#'
# leaves line 2 as bare YAML and breaks the file it is supposed to label.
HASH_BANNER = "\n".join("# " + line for line in BANNER.splitlines())

ROUTER_SKILL = "telegram"

# Sections lifted verbatim from the router skill, matched by heading prefix so a
# reworded heading does not silently drop content.
ROUTER_SECTIONS = ("Step 0", "Step 1", "The Invariants", "Escalation",
                   "Red Flags", "Quick Reference")


# --------------------------------------------------------------------------- #
# model
# --------------------------------------------------------------------------- #

@dataclass
class Skill:
    name: str
    description: str
    title: str
    body: str
    rel_dir: str
    references: list[str] = field(default_factory=list)
    ref_words: int = 0

    @property
    def is_router(self) -> bool:
        return self.name == ROUTER_SKILL


def parse_skill(skill_md: pathlib.Path, skills_dir: pathlib.Path) -> Skill:
    raw = skill_md.read_text(encoding="utf-8")
    m = re.match(r"^---\n(.*?)\n---\n(.*)$", raw, re.S)
    if not m:
        raise ValueError(f"{skill_md}: no YAML frontmatter")
    fm, body = m.group(1), m.group(2).lstrip("\n")

    name = _fm_value(fm, "name")
    desc = " ".join(_fm_value(fm, "description").split())
    if not name or not desc:
        raise ValueError(f"{skill_md}: frontmatter needs name and description")

    title_m = re.search(r"^#\s+(.+)$", body, re.M)
    title = title_m.group(1).strip() if title_m else name

    refdir = skill_md.parent / "references"
    refs = sorted(p.name for p in refdir.glob("*.md")) if refdir.is_dir() else []

    return Skill(name=name, description=desc, title=title, body=body,
                 rel_dir=skill_md.parent.relative_to(skills_dir).as_posix(),
                 references=refs,
                 ref_words=sum(wc((refdir / r).read_text(encoding="utf-8"))
                               for r in refs))


def _fm_value(fm: str, key: str) -> str:
    m = re.search(rf"^{key}:\s*(.+?)(?=\n[a-z_]+:|\Z)", fm, re.S | re.M)
    return m.group(1).strip() if m else ""


def load_skills(skills_dir: pathlib.Path) -> list[Skill]:
    found = sorted(skills_dir.glob("*/SKILL.md"))
    if not found:
        raise SystemExit(f"no SKILL.md under {skills_dir}")
    skills = [parse_skill(p, skills_dir) for p in found]
    skills.sort(key=lambda s: (not s.is_router, s.name))     # router first
    if not skills[0].is_router:
        print(f"warning: no {ROUTER_SKILL!r} skill found; the router will be thin",
              file=sys.stderr)
    return skills


# --------------------------------------------------------------------------- #
# path rewriting — adapters live in the user's project, the skills live in the stack
# --------------------------------------------------------------------------- #

def rewrite_paths(body: str, *, skill: Skill, stack: str, names: set[str]) -> str:
    """Turn skill-relative references into project-relative paths, so an agent
    that cannot 'load a skill by name' can still open the file."""
    out = body

    # `telegram-ux` -> `<stack>/skills/telegram-ux/SKILL.md`
    for n in sorted(names, key=len, reverse=True):
        if n == skill.name:
            continue
        out = out.replace(f"`{n}`", f"`{stack}/skills/{n}/SKILL.md`")

    # `references/foo.md` -> resolved against THIS skill's directory
    out = re.sub(r"`references/([a-z0-9.\-]+\.md)`",
                 lambda m: f"`{stack}/skills/{skill.rel_dir}/references/{m.group(1)}`",
                 out)
    # `telegram-ux/references/foo.md` -> full path
    out = re.sub(r"`(telegram[a-z\-]*)/references/([a-z0-9.\-]+\.md)`",
                 lambda m: f"`{stack}/skills/{m.group(1)}/references/{m.group(2)}`", out)

    out = out.replace("`scripts/", f"`{stack}/scripts/")
    out = out.replace("python scripts/", f"python {stack}/scripts/")
    out = out.replace("`workflows/WORKFLOW.md`", f"`{stack}/workflows/WORKFLOW.md`")
    out = out.replace("`templates/", f"`{stack}/templates/")
    return out


def sections(body: str) -> list[tuple[str, str]]:
    """Split on '## ' headings, preserving order."""
    parts = re.split(r"\n(?=## )", body)
    out = []
    for p in parts:
        m = re.match(r"##\s+(.+)", p)
        out.append((m.group(1).strip() if m else "", p.strip()))
    return out


def wc(text: str) -> int:
    return len(text.split())


def yscalar(s: str) -> str:
    """Always double-quote a YAML scalar. Descriptions contain ': ', '"' and '#',
    each of which makes a plain scalar invalid or ambiguous — and a rule file with
    unparseable frontmatter is silently ignored by the harness."""
    return '"' + " ".join(s.split()).replace("\\", "\\\\").replace('"', '\\"') + '"'


def cell(s: str) -> str:
    """Make a string safe inside a markdown table cell. The MarkdownV2 reserved
    list in telegram-text contains a literal `|`, which silently breaks the
    table it lands in — escape it rather than truncating around it."""
    return " ".join(s.split()).replace("|", "\\|")


# --------------------------------------------------------------------------- #
# the compressed router
# --------------------------------------------------------------------------- #

def build_router(skills: list[Skill], stack: str) -> str:
    names = {s.name for s in skills}
    router = next((s for s in skills if s.is_router), None)

    index = ["| File | Open it when |", "|---|---|"]
    for s in skills:
        if s.is_router:
            continue
        trigger = re.sub(r"^Use when\s+", "", s.description).rstrip(".")
        index.append(f"| **`{stack}/skills/{s.rel_dir}/SKILL.md`**<br/>"
                     f"{cell(s.title)} | {cell(trigger)} |")
        for r in s.references:
            index.append(f"| ↳ `{stack}/skills/{s.rel_dir}/references/{r}` "
                         f"| deeper reference for the above |")

    head = [
        f"<!-- {BANNER} -->",
        "",
        "# Telegram work — routing rules",
        "",
        "This is a compressed router. The full guidance lives in the files listed "
        "below; **open the ones your task touches before writing code.** Do not "
        "work from memory: the Bot API changed nine times between 2025-04 and "
        "2026-07.",
        "",
        "## Files",
        "",
        *index,
        "",
        f"Process for non-trivial work: `{stack}/workflows/WORKFLOW.md` "
        "(8 stages, Brief to Ship). You may not write handlers before the "
        "Navigation Contract exists and validates.",
        "",
    ]

    kept: list[str] = []
    if router:
        rewritten = rewrite_paths(router.body, skill=router, stack=stack, names=names)
        for heading, text in sections(rewritten):
            if heading.startswith(ROUTER_SECTIONS):
                # "Step 1 — Route" duplicates the Files table above
                if heading.startswith("Step 1"):
                    continue
                kept.append(text)
    return "\n".join(head + kept).rstrip() + "\n"


# --------------------------------------------------------------------------- #
# targets
# --------------------------------------------------------------------------- #

def t_cursor(skills, stack, router):
    """One .mdc per skill. The router is always applied; the rest are picked by
    description, which keeps the lazy-loading behaviour Claude Code has."""
    names = {s.name for s in skills}
    files = {}
    for s in skills:
        body = rewrite_paths(s.body, skill=s, stack=stack, names=names)
        fm = ["---", f"description: {yscalar(s.description)}", "globs:",
              f"alwaysApply: {'true' if s.is_router else 'false'}", "---", ""]
        if s.is_router:
            body = router
        files[f".cursor/rules/{s.name}.mdc"] = "\n".join(fm) + body
    return files


def t_windsurf(skills, stack, router):
    names = {s.name for s in skills}
    files = {}
    for s in skills:
        trigger = "always_on" if s.is_router else "model_decision"
        fm = ["---", f"trigger: {trigger}", f"description: {yscalar(s.description)}",
              "---", ""]
        body = router if s.is_router else rewrite_paths(
            s.body, skill=s, stack=stack, names=names)
        files[f".windsurf/rules/{s.name}.md"] = "\n".join(fm) + body
    return files


def t_continue(skills, stack, router):
    names = {s.name for s in skills}
    files = {}
    for s in skills:
        fm = ["---", f"name: {s.name}",
              f"description: {yscalar(s.description)}", "---", ""]
        body = router if s.is_router else rewrite_paths(
            s.body, skill=s, stack=stack, names=names)
        files[f".continue/rules/{s.name}.md"] = "\n".join(fm) + body
    return files


def t_cline(skills, stack, router):
    names = {s.name for s in skills}
    files = {f".clinerules/00-{ROUTER_SKILL}.md": router}
    for s in skills:
        if s.is_router:
            continue
        files[f".clinerules/{s.name}.md"] = rewrite_paths(
            s.body, skill=s, stack=stack, names=names)
    return files


def t_copilot(skills, stack, router):
    return {".github/copilot-instructions.md": router}


def t_agents(skills, stack, router):
    """AGENTS.md — read by Codex and a growing list of others."""
    return {"AGENTS.md": router}


def t_zed(skills, stack, router):
    return {".rules": router}


def t_aider(skills, stack, router):
    conf = (f"{HASH_BANNER}\n"
            "read:\n"
            "  - CONVENTIONS.md\n"
            "auto-commits: false\n")
    return {"CONVENTIONS.md": router, ".aider.conf.yml": conf}


def t_ci(skills, stack, router):
    """The part that survives any harness: gates with exit codes."""
    workflow = f"""{HASH_BANNER}
name: telegram-gates

on: [push, pull_request]

jobs:
  gates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {{python-version: '3.12'}}
      - run: pip install pyyaml
      - name: install ffprobe (exact WEBM validation)
        run: sudo apt-get update && sudo apt-get install -y ffmpeg
      - name: Bot API version guard
        run: python {stack}/scripts/check_api_version.py --pinned 10.2
      - name: navigation contract
        run: python {stack}/scripts/gen_navigation.py navigation.yaml --check
        if: hashFiles('navigation.yaml') != ''
      - name: invariants
        run: python {stack}/scripts/tg_preflight.py --project .
"""
    precommit = f"""{HASH_BANNER}
repos:
  - repo: local
    hooks:
      - id: tg-lint
        name: telegram invariants
        entry: python {stack}/scripts/tg_lint.py
        language: system
        pass_filenames: true
        types_or: [python, ts, tsx, css]
      - id: tg-contract
        name: navigation contract
        entry: python {stack}/scripts/gen_navigation.py navigation.yaml --check
        language: system
        pass_filenames: false
        files: ^navigation\\.yaml$
"""
    makefile = f"""{HASH_BANNER}
STACK := {stack}

.PHONY: gates nav lint assets preflight

gates: preflight

preflight:
\tpython $(STACK)/scripts/tg_preflight.py --project .

nav:
\tpython $(STACK)/scripts/gen_navigation.py navigation.yaml --out app/nav --diagram nav.mmd

lint:
\tpython $(STACK)/scripts/tg_lint.py app --rules formatting,callback,gateway,layers,secrets,presence

assets:
\tpython $(STACK)/scripts/make_process_assets.py --out assets/process-emoji
\tpython $(STACK)/scripts/validate_sticker_assets.py assets/process-emoji --kind custom_emoji
"""
    return {".github/workflows/telegram-gates.yml": workflow,
            ".pre-commit-config.yaml": precommit,
            "Makefile.telegram": makefile}


TARGETS = {
    "cursor":   ("Cursor", ".cursor/rules/*.mdc", t_cursor),
    "windsurf": ("Windsurf", ".windsurf/rules/*.md", t_windsurf),
    "continue": ("Continue", ".continue/rules/*.md", t_continue),
    "cline":    ("Cline", ".clinerules/*.md", t_cline),
    "copilot":  ("GitHub Copilot / VS Code", ".github/copilot-instructions.md", t_copilot),
    "agents":   ("Codex and AGENTS.md readers", "AGENTS.md", t_agents),
    "zed":      ("Zed", ".rules", t_zed),
    "aider":    ("Aider", "CONVENTIONS.md + .aider.conf.yml", t_aider),
    "ci":       ("CI and pre-commit (harness-independent)",
                 ".github/workflows + .pre-commit-config.yaml + Makefile.telegram", t_ci),
}

NATIVE = ("Claude Code (~/.claude/skills), Codex CLI, Copilot CLI and Gemini CLI "
          "(~/.agents/skills) read SKILL.md directories directly — use install.sh, "
          "no adapter needed.")


# --------------------------------------------------------------------------- #

def main(argv: list[str]) -> int:
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8", errors="replace")
        except (AttributeError, ValueError):
            pass

    here = pathlib.Path(__file__).resolve().parent.parent
    p = argparse.ArgumentParser(description=__doc__,
                               formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--out", type=pathlib.Path,
                   help="project root to write adapters into")
    p.add_argument("--skills-dir", type=pathlib.Path, default=here / "skills")
    p.add_argument("--stack-path", default="telegram-stack",
                   help="path from the project root to this repo (default: telegram-stack)")
    p.add_argument("--targets", default="all")
    p.add_argument("--dry-run", action="store_true")
    p.add_argument("--list", action="store_true")
    a = p.parse_args(argv[1:])

    if a.list:
        print("targets:")
        for k, (label, where, _) in TARGETS.items():
            print(f"  {k:<9} {label:<38} -> {where}")
        print(f"\nnative: {NATIVE}")
        return 0
    if not a.out:
        print("need --out <project root> (or --list)", file=sys.stderr)
        return 2
    if not a.skills_dir.is_dir():
        print(f"skills dir not found: {a.skills_dir}", file=sys.stderr)
        return 2

    wanted = set(TARGETS) if a.targets == "all" else {
        t.strip() for t in a.targets.split(",") if t.strip()}
    unknown = wanted - set(TARGETS)
    if unknown:
        print(f"unknown targets: {sorted(unknown)}; known: {sorted(TARGETS)}",
              file=sys.stderr)
        return 2

    try:
        skills = load_skills(a.skills_dir)
    except ValueError as e:
        print(f"skill parse error: {e}", file=sys.stderr)
        return 1

    stack = a.stack_path.rstrip("/")
    router = build_router(skills, stack)

    skill_words = sum(wc(s.body) for s in skills)
    ref_words = sum(s.ref_words for s in skills)
    n_refs = sum(len(s.references) for s in skills)
    total = skill_words + ref_words
    print(f"{len(skills)} skills ({skill_words:,} words) + {n_refs} references "
          f"({ref_words:,} words) = {total:,} words")
    print(f"compressed router: {wc(router):,} words — "
          f"{wc(router) / max(total, 1):.0%} of the full set. Everything else is "
          f"read on demand from the paths it lists.\n")

    written = 0
    for key in sorted(wanted):
        label, _, fn = TARGETS[key]
        files = fn(skills, stack, router)
        print(f"{label}")
        for relpath, content in sorted(files.items()):
            dest = a.out / relpath
            note = f"    {relpath:<46} {wc(content):>6} words"
            if a.dry_run:
                print(note + "   (dry-run)")
                continue
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_text(content, encoding="utf-8")
            written += 1
            print(note)
        print()

    if a.dry_run:
        print("--dry-run: nothing written")
    else:
        print(f"{written} file(s) written under {a.out.resolve()}")
    print(f"\nnative: {NATIVE}")
    print("Regenerate after any change to skills/ — adapters are generated, "
          "not maintained.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
