#!/usr/bin/env python3
"""tg_lint — machine-enforced Telegram invariants.

Rules an agent cannot argue with. Each finding is `file:line  RULE  message`.

    python tg_lint.py app/                       # all rules
    python tg_lint.py app/ --rules formatting,callback
    python tg_lint.py . --rules theme,miniapp --format json

Rule groups
  formatting  MarkdownV2, unescaped interpolation, hand-computed entity offsets
  callback    callback_data grammar, 64-byte budget, f-strings
  gateway     direct bot.send_* / bot.edit_* outside app/tg/
  layers      handlers/ and api/ importing repositories, integrations or SQL
  secrets     hardcoded tokens, tokens in logs
  presence    callbacks answered, terminal presence states
  theme       hex colours and 100vh in Mini App styles
  miniapp     user id read from request payload instead of the session

Exit: 0 clean, 1 findings, 2 usage error.
"""
from __future__ import annotations

import argparse
import ast
import json
import pathlib
import re
import sys

PY_SKIP_DIRS = {".git", ".venv", "venv", "node_modules", "__pycache__",
                "dist", "build", ".mypy_cache", ".pytest_cache", "migrations"}
GENERATED_MARKER = "GENERATED by scripts/gen_navigation.py"

Finding = tuple[str, int, str, str]   # file, line, rule, message


# --------------------------------------------------------------------------- #
# helpers
# --------------------------------------------------------------------------- #

def iter_files(root: pathlib.Path, suffixes: tuple[str, ...]):
    if root.is_file():
        if root.suffix in suffixes:
            yield root
        return
    for p in root.rglob("*"):
        if p.is_dir() or p.suffix not in suffixes:
            continue
        if any(part in PY_SKIP_DIRS for part in p.parts):
            continue
        yield p


def kw(call: ast.Call, name: str):
    for k in call.keywords:
        if k.arg == name:
            return k.value
    return None


def is_interpolated(node) -> bool:
    """f-string, %-format, .format(), or a + concat of a non-literal."""
    if isinstance(node, ast.JoinedStr):
        return True
    if isinstance(node, ast.BinOp) and isinstance(node.op, (ast.Mod, ast.Add)):
        return True
    if isinstance(node, ast.Call) and isinstance(node.func, ast.Attribute) \
            and node.func.attr == "format":
        return True
    return False


def dotted(node) -> str:
    parts = []
    while isinstance(node, ast.Attribute):
        parts.append(node.attr)
        node = node.value
    if isinstance(node, ast.Name):
        parts.append(node.id)
    return ".".join(reversed(parts))


def rel(p: pathlib.Path, root: pathlib.Path) -> str:
    try:
        return str(p.relative_to(root if root.is_dir() else root.parent))
    except ValueError:
        return str(p)


# --------------------------------------------------------------------------- #
# python AST rules
# --------------------------------------------------------------------------- #

SEND_METHODS = re.compile(r"^(send|edit|delete|answer|copy|forward|set)[a-z_]")
# One-shot startup/lifecycle calls: they belong in the composition root, and a
# per-chat limiter is meaningless for them.
LIFECYCLE_METHODS = {
    "set_webhook", "delete_webhook", "get_webhook_info", "get_me",
    "set_my_commands", "delete_my_commands", "set_my_description",
    "set_my_short_description", "set_my_name", "set_chat_menu_button",
    "set_my_default_administrator_rights", "close", "log_out",
    "get_updates", "set_my_profile_photo",
}
TOKEN_RE = re.compile(r"\b\d{8,12}:[A-Za-z0-9_-]{30,50}")


def lint_python(path: pathlib.Path, src: str, rules: set[str],
                root: pathlib.Path) -> list[Finding]:
    out: list[Finding] = []
    if GENERATED_MARKER in src:
        return out
    fname = rel(path, root)
    parts = set(path.parts)
    try:
        tree = ast.parse(src, filename=str(path))
    except SyntaxError as e:
        return [(fname, e.lineno or 0, "parse", f"syntax error: {e.msg}")]

    # Escape hatch for deliberate fixtures: `# tg-lint: ignore[secrets]`
    lines = src.splitlines()

    def suppressed(lineno: int, rule: str) -> bool:
        if not 1 <= lineno <= len(lines):
            return False
        return f"tg-lint: ignore[{rule}]" in lines[lineno - 1]

    if "secrets" in rules:
        for m in TOKEN_RE.finditer(src):
            line = src[:m.start()].count("\n") + 1
            if suppressed(line, "secrets"):
                continue
            out.append((fname, line, "secrets",
                        "hardcoded bot token — move to the environment and rotate it"))

    for node in ast.walk(tree):
        ln = getattr(node, "lineno", 0)
        if ln and any(f"tg-lint: ignore[{r}]" in lines[ln - 1]
                      for r in rules if ln <= len(lines)):
            continue
        # ---------------- formatting ----------------
        if "formatting" in rules and isinstance(node, ast.Call):
            pm = kw(node, "parse_mode")
            if isinstance(pm, ast.Constant) and isinstance(pm.value, str):
                if pm.value.lower().startswith("markdown"):
                    out.append((fname, node.lineno, "formatting",
                                f"parse_mode={pm.value!r} is banned — use tg_text.H (HTML) "
                                "or tg_text.E (entities)"))
            if pm is not None:
                for name in ("text", "caption", "message_text", "question"):
                    v = kw(node, name)
                    if v is not None and is_interpolated(v):
                        out.append((fname, node.lineno, "formatting",
                                    f"{name}= is interpolated while parse_mode is set — "
                                    "escape at the interpolation site with tg_text.H"))
                if node.args and is_interpolated(node.args[-1]):
                    out.append((fname, node.lineno, "formatting",
                                "positional text is interpolated while parse_mode is set — "
                                "use tg_text.H"))
            if dotted(node.func).endswith("MessageEntity"):
                off = kw(node, "offset")
                if isinstance(off, ast.Constant) and isinstance(off.value, int):
                    out.append((fname, node.lineno, "formatting",
                                "hand-computed entity offset — offsets are UTF-16 code units, "
                                "use tg_text.E"))
            if dotted(node.func) == "html.escape":
                out.append((fname, node.lineno, "formatting",
                            "html.escape also escapes quotes; use tg_text.H"))

        # ---------------- callback ----------------
        if "callback" in rules and isinstance(node, ast.Call):
            cd = kw(node, "callback_data")
            if cd is not None:
                if is_interpolated(cd):
                    out.append((fname, node.lineno, "callback",
                                "callback_data built by interpolation — use CB.pack(); "
                                "the protocol is v1:domain:action:arg"))
                elif isinstance(cd, ast.Constant) and isinstance(cd.value, str):
                    v = cd.value
                    if len(v.encode()) > 64:
                        out.append((fname, node.lineno, "callback",
                                    f"callback_data is {len(v.encode())} bytes (max 64)"))
                    if not re.match(r"^v\d+:[a-z][a-z0-9_]*:[a-z][a-z0-9_]*", v):
                        out.append((fname, node.lineno, "callback",
                                    f"callback_data {v!r} does not match v<N>:domain:action"))

        # ---------------- gateway ----------------
        if "gateway" in rules and isinstance(node, ast.Call) \
                and isinstance(node.func, ast.Attribute):
            recv = dotted(node.func)
            if re.match(r"^(bot|self\.bot|ctx\.bot|message\.bot)\.", recv) \
                    and SEND_METHODS.match(node.func.attr) \
                    and node.func.attr not in LIFECYCLE_METHODS:
                if "tg" not in parts and "tests" not in parts:
                    out.append((fname, node.lineno, "gateway",
                                f"{recv} bypasses the gateway — no limiter, no retry, no logs"))

        # ---------------- layers ----------------
        if "layers" in rules and isinstance(node, (ast.Import, ast.ImportFrom)):
            mod = node.module if isinstance(node, ast.ImportFrom) else \
                (node.names[0].name if node.names else "")
            mod = mod or ""
            if {"handlers", "api"} & parts:
                for bad in ("repositories", "integrations", "sqlalchemy", "asyncpg", "psycopg"):
                    if bad in mod:
                        out.append((fname, node.lineno, "layers",
                                    f"{'handlers' if 'handlers' in parts else 'api'}/ "
                                    f"must not import {bad} — go through services/"))
            if "services" in parts and mod.startswith(("aiogram", "telegram", "telebot")):
                out.append((fname, node.lineno, "layers",
                            "services/ must not import a Telegram framework — "
                            "it is shared with the Mini App backend"))

        # ---------------- presence ----------------
        if "presence" in rules and isinstance(node, ast.AsyncFunctionDef):
            body = ast.dump(node)
            takes_cb = any(a.arg in ("cb", "callback", "callback_query", "query")
                           for a in node.args.args)
            if takes_cb and "answer" not in body:
                out.append((fname, node.lineno, "presence",
                            f"{node.name}() handles a callback but never answers it — "
                            "a 30s spinner is what the user sees"))

        # ---------------- secrets in logs ----------------
        if "secrets" in rules and isinstance(node, ast.Call):
            f = dotted(node.func)
            if re.match(r"^(log|logger|logging)\.(debug|info|warning|error|exception)$", f):
                for a in list(node.args) + [k.value for k in node.keywords]:
                    if isinstance(a, ast.Attribute) and a.attr in ("token", "bot_token",
                                                                    "init_data", "initData"):
                        out.append((fname, node.lineno, "secrets",
                                    f"logging .{a.attr} — never log tokens or raw initData"))
        if "presence" in rules and isinstance(node, ast.ExceptHandler):
            if node.type is None and all(isinstance(s, ast.Pass) for s in node.body):
                out.append((fname, node.lineno, "presence",
                            "bare `except: pass` — every error maps to a named action "
                            "(see telegram/references/errors.md)"))
    return out


# --------------------------------------------------------------------------- #
# text rules: Mini App styles and routes
# --------------------------------------------------------------------------- #

HEX_RE = re.compile(r"(?<![\w-])#[0-9a-fA-F]{3,8}\b")
VH_RE = re.compile(r"\b\d+vh\b")
TOKENS_OK = ("theme.css", "tokens.css", "tokens.yaml", "variables.css")


def lint_styles(path: pathlib.Path, src: str, root: pathlib.Path) -> list[Finding]:
    out: list[Finding] = []
    if path.name in TOKENS_OK:
        return out
    for i, line in enumerate(src.splitlines(), 1):
        if line.lstrip().startswith(("//", "/*", "*")):
            continue
        if HEX_RE.search(line) and "--tg-" not in line:
            out.append((rel(path, root), i, "theme",
                        "hardcoded colour — use a themeParams token from theme.css"))
        if VH_RE.search(line) and "dvh" not in line:
            out.append((rel(path, root), i, "theme",
                        "vh units jump when the keyboard opens — use --vh-stable "
                        "(viewportStableHeight)"))
    return out


USERID_FROM_PAYLOAD = re.compile(
    r"(body|payload|request\.(json|form|args|query_params)|req\.body|data)"
    r"\s*(\.|\[)\s*[\"']?(user_?id|tg_?id|telegram_?id)", re.I)


def lint_miniapp_routes(path: pathlib.Path, src: str, root: pathlib.Path) -> list[Finding]:
    out: list[Finding] = []
    for i, line in enumerate(src.splitlines(), 1):
        if USERID_FROM_PAYLOAD.search(line):
            out.append((rel(path, root), i, "miniapp",
                        "user id read from the request payload — the verified session is "
                        "the only source of identity"))
    return out


# --------------------------------------------------------------------------- #

ALL_RULES = {"formatting", "callback", "gateway", "layers",
             "secrets", "presence", "theme", "miniapp"}


def run(root: pathlib.Path, rules: set[str]) -> list[Finding]:
    findings: list[Finding] = []
    py_rules = rules & {"formatting", "callback", "gateway", "layers",
                        "secrets", "presence"}
    if py_rules:
        for p in iter_files(root, (".py",)):
            findings += lint_python(p, p.read_text(encoding="utf-8", errors="replace"),
                                    py_rules, root)
    if "theme" in rules:
        for p in iter_files(root, (".css", ".scss", ".tsx", ".jsx", ".ts", ".vue")):
            findings += lint_styles(p, p.read_text(encoding="utf-8", errors="replace"), root)
    if "miniapp" in rules:
        for p in iter_files(root, (".py", ".ts", ".js")):
            findings += lint_miniapp_routes(
                p, p.read_text(encoding="utf-8", errors="replace"), root)
    return sorted(set(findings))


def main(argv: list[str]) -> int:
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8", errors="replace")
        except (AttributeError, ValueError):
            pass
    p = argparse.ArgumentParser(description=__doc__,
                               formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("path", type=pathlib.Path)
    p.add_argument("--rules", default="all")
    p.add_argument("--format", choices=("text", "json"), default="text")
    a = p.parse_args(argv[1:])

    rules = ALL_RULES if a.rules == "all" else {r.strip() for r in a.rules.split(",")}
    unknown = rules - ALL_RULES
    if unknown:
        print(f"unknown rules: {sorted(unknown)}; known: {sorted(ALL_RULES)}", file=sys.stderr)
        return 2
    if not a.path.exists():
        print(f"path not found: {a.path}", file=sys.stderr)
        return 2

    findings = run(a.path, rules)
    if a.format == "json":
        print(json.dumps([{"file": f, "line": l, "rule": r, "message": m}
                          for f, l, r, m in findings], ensure_ascii=False, indent=1))
    else:
        for f, l, r, m in findings:
            print(f"{f}:{l}  {r.upper():10} {m}")
        by_rule: dict[str, int] = {}
        for _, _, r, _ in findings:
            by_rule[r] = by_rule.get(r, 0) + 1
        if findings:
            print(f"\n{len(findings)} finding(s): " +
                  ", ".join(f"{k}={v}" for k, v in sorted(by_rule.items())))
        else:
            print(f"tg_lint: clean ({', '.join(sorted(rules))})")
    return 1 if findings else 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
