"""The Presence Protocol — make the bot's internal state visible in the chat.

One process state -> one bundle of three signals, emitted together, always:
  reaction on the USER's message  (which phase, survives scrolling)
  status line in OUR message, edited in place  (the phase in words + animated glyph)
  chat action  (native liveness; the only signal available before any message)

The context manager guarantees a terminal state. A process that ends in a
non-terminal state is a bug, not an edge case: it leaves a permanent
"Работаю..." in someone's chat.

Spec: skills/telegram-presence/SKILL.md
"""
from __future__ import annotations

import asyncio
import logging
from dataclasses import dataclass
from enum import Enum

from .errors import user_safe_reason
from .text import E

try:                                     # generated by build_process_pack.py
    from ..nav.custom_emoji import CUSTOM, FALLBACK
except ImportError:                      # a missing set must never break a message
    CUSTOM: dict[str, str | None] = {}
    FALLBACK: dict[str, str] = {}

log = logging.getLogger("tg.presence")
ACTION_HEARTBEAT_SEC = 4.0               # sendChatAction expires after ~5 s


class ProcState(str, Enum):
    RECEIVED = "RECEIVED"
    QUEUED = "QUEUED"
    STUDYING = "STUDYING"
    WORKING = "WORKING"
    WAITING_USER = "WAITING_USER"
    WAITING_HUMAN = "WAITING_HUMAN"
    DONE = "DONE"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


TERMINAL = frozenset({ProcState.DONE, ProcState.FAILED, ProcState.CANCELLED})


@dataclass(frozen=True)
class Spec:
    key: str                # glyph key in the Process Pack
    reaction: str | None    # emoji placed on the user's message
    status: str | None      # words in our status line
    action: str | None      # chat action


# Canonical vocabulary. Do not invent per-project names: predictability across
# bots is the point. Reaction emoji must be in Telegram's allowed reaction set.
PRESENCE: dict[ProcState, Spec] = {
    ProcState.RECEIVED:      Spec("received", "👀", None, "typing"),
    ProcState.QUEUED:        Spec("queued", "⏳", "В очереди", "typing"),
    ProcState.STUDYING:      Spec("studying", "🔎", "Изучаю запрос", "typing"),
    ProcState.WORKING:       Spec("working", "✍️", "Работаю", "typing"),
    ProcState.WAITING_USER:  Spec("waiting_user", "✋", "Жду ответа", None),
    ProcState.WAITING_HUMAN: Spec("waiting_human", "🕐", "На проверке", None),
    ProcState.DONE:          Spec("done", "✅", None, None),
    ProcState.FAILED:        Spec("failed", "⚠️", "Не получилось", None),
    ProcState.CANCELLED:     Spec("cancelled", "🚫", "Отменено", None),
}

# Fallback if Telegram rejects our reaction for this chat (the allowed set is
# server-controlled). Degrading a reaction into a message would be a bug.
SAFE_REACTION = "👍"


class Presence:
    """One instance per unit of work.

        async with Presence(gw, chat_id, msg.message_id, trace_id=tid) as p:
            await p.set(ProcState.STUDYING)
            ...
            await p.set(ProcState.WORKING, progress=(i, n))
    """

    def __init__(self, gw, chat_id: int, user_message_id: int, *,
                 trace_id: str = "-", min_visible_sec: float = 0.3):
        self.gw = gw
        self.chat_id = chat_id
        self.umid = user_message_id
        self.trace_id = trace_id
        self.min_visible = min_visible_sec
        self.status_message_id: int | None = None
        self.state: ProcState | None = None
        self._action_task: asyncio.Task | None = None
        self._started = asyncio.get_event_loop().time()

    # --------------------------------------------------------------- public
    async def set(self, state: ProcState, detail: str = "", *,
                  progress: tuple[int, int] | None = None) -> None:
        spec = PRESENCE[state]
        self.state = state

        await self._react(spec)
        await self._status(spec, detail, progress)
        await self._retune_action(spec.action)

        log.info("presence", extra={"event": "presence", "presence_state": state.value,
                                    "detail": detail or None})

    async def replace_with_result(self, text: str, entities=None, **kw):
        """DONE + the answer in one place: the status message becomes the answer.
        Prevents a dead 'Работаю...' sitting next to the result."""
        await self.set(ProcState.DONE)
        if self.status_message_id is not None:
            edited = await self.gw.edit_message_text(
                self.chat_id, self.status_message_id, text, entities=entities,
                soft=True, **kw)
            if edited is not None:
                return edited
        return await self.gw.send_message(
            self.chat_id, text, entities=entities,
            reply_parameters={"message_id": self.umid}, **kw)

    # -------------------------------------------------------------- internal
    async def _react(self, spec: Spec) -> None:
        if not spec.reaction:
            return
        r = await self.gw.set_message_reaction(
            self.chat_id, self.umid, [{"type": "emoji", "emoji": spec.reaction}],
            soft=True)
        if r is None and spec.reaction != SAFE_REACTION:
            await self.gw.set_message_reaction(
                self.chat_id, self.umid,
                [{"type": "emoji", "emoji": SAFE_REACTION}], soft=True)

    async def _status(self, spec: Spec, detail: str,
                      progress: tuple[int, int] | None) -> None:
        if not spec.status:
            return
        text, ents = self._render(spec, detail, progress)
        if self.status_message_id is None:
            # do not flash a status for work that finishes instantly
            elapsed = asyncio.get_event_loop().time() - self._started
            if elapsed < self.min_visible and self.state in (ProcState.RECEIVED,):
                return
            m = await self.gw.send_message(
                self.chat_id, text, entities=ents,
                reply_parameters={"message_id": self.umid})
            self.status_message_id = getattr(m, "message_id", None)
        else:
            await self.gw.edit_status(self.chat_id, self.status_message_id,
                                      text, entities=ents)

    def _render(self, spec: Spec, detail: str, progress):
        b = E()
        fallback = FALLBACK.get(spec.key) or spec.reaction or "•"
        b.emoji(fallback, CUSTOM.get(spec.key)).text(" ").bold(spec.status or "")
        if progress:
            b.text(" · ").code(f"{progress[0]}/{progress[1]}")
        if detail:
            b.nl().text(detail)
        return b.build()

    async def _retune_action(self, action: str | None) -> None:
        await self._stop_action()
        if not action:
            return
        self._action_task = asyncio.create_task(
            self._action_loop(action), name=f"presence-action:{self.chat_id}")

    async def _action_loop(self, action: str) -> None:
        try:
            while True:
                await self.gw.send_chat_action(self.chat_id, action)
                await asyncio.sleep(ACTION_HEARTBEAT_SEC)
        except asyncio.CancelledError:
            raise
        except Exception:                                       # noqa: BLE001
            log.debug("presence", extra={"event": "presence",
                                          "detail": "chat action loop stopped"})

    async def _stop_action(self) -> None:
        if self._action_task and not self._action_task.done():
            self._action_task.cancel()
            try:
                await self._action_task
            except asyncio.CancelledError:
                pass
        self._action_task = None

    # ----------------------------------------------------------- lifecycle
    async def __aenter__(self) -> "Presence":
        await self.set(ProcState.RECEIVED)
        return self

    async def __aexit__(self, exc_type, exc, tb) -> bool:
        await self._stop_action()
        if self.state not in TERMINAL:
            if exc_type is None:
                await self.set(ProcState.DONE)
            elif issubclass(exc_type, asyncio.CancelledError):
                await self.set(ProcState.CANCELLED)
            else:
                await self.set(ProcState.FAILED, user_safe_reason(exc))
        return False                       # never swallow the exception
